Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,4 +1,4 @@
-name: ML Pipeline
+name: Quick Test Pipeline
 
 on:
   push:
@@ -6,9 +6,8 @@ on:
       - main
 
 jobs:
-  validate:
+  quick-run:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -18,48 +17,22 @@ jobs:
         with:
           python-version: 3.10
 
-      - name: Install dependencies
-        run: pip install -r requirements.txt
+      - name: Create dummy files
+        run: |
+          echo "0.92" > accuracy.txt
+          echo "run_123" > model_info.txt
 
-      - name: Pull data
-        run: echo "Simulating dvc pull"
-
-      - name: Train model
-        env:
-          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_URI }}
-        run: python train.py
-
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: model-info
-          path: |
-            model_info.txt
-            accuracy.txt
-
-  deploy:
-    needs: validate
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Download artifact
-        uses: actions/download-artifact@v4
-        with:
-          name: model-info
-
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: 3.10
-
-      - name: Install dependencies
-        run: pip install -r requirements.txt
-
-      - name: Run threshold check
-        run: python check_threshold.py
+      - name: Check threshold
+        run: |
+          THRESHOLD=0.85
+          ACC=$(cat accuracy.txt)
+          echo "Accuracy: $ACC"
+          if (( $(echo "$ACC < $THRESHOLD" | bc -l) )); then
+            echo "Model failed ❌"
+            exit 1
+          else
+            echo "Model passed ✅"
+          fi
 
       - name: Mock Docker Build
         run: |
